### ISSUE TITLE
Потеряные кавычки при конвертации

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cepreu2github/bqt2mod#1]
```
What steps will reproduce the problem?
1. Начать конвертировать модуль из Цитаты, в 
котором есть кавычки "
2. Подключить полученный модуль в Sword
3. Места, в которых изначально были кавычки, 
в Sword уже без них.

What is the expected output? What do you see instead?
Ожидалось увидеть кавычки там, где они были 
ранее.

What version of the product are you using? On what operating system?
0.8.5 на Debian GNU/Linux
Sword с разными фронт-эндами: Xiphos, BibleTime, 
BibleDesktop, diatheke

Please provide any additional information below.
Кавычек нет и в промежуточном osis xml файле. 
Нестандартные кавычки («»„“) сохраняются.

```

Original issue reported on code.google.com by `kos.ivan...@gmail.com` on 13 Dec 2012 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
пропавшие кавычки были в модуле Цитаты в html 
представлены в виде "
```

Original comment by `kos.ivan...@gmail.com` on 13 Dec 2012 at 9:56

**Comment by cepreu2github** [comment]
Оригинальные кавычки использовали [HTML Special Entities](http://www.htmlhelp.com/reference/html40/entities/special.html). Конвертер не поддерживает работу ними. Есть workaround - перекодировать модуль в Unicode, сделать полнотекстовый поиск и замену special entities на соответствующие символы Unicode, а затем результат отдать на вход конвертеру.
Возможно когда-нибудь поработаю над добавление поддержки HTML Special Entities, но пока таких планов нет. Тем не менее, открыт для Pull Request'ов, добавляющих эту функциональность.
